[workspace]
changelog_update = false
dependencies_update = false
git_release_enable = false
git_tag_enable = false
pr_labels = ["release"]
publish_timeout = "10m"
release_always = false
semver_check = false

[[package]]
name = "workshop-rs"
version_group = "workshop-rs"
changelog_include = ["workshop-rs-cli"]
git_tag_enable = true
git_tag_name = "v{{ version }}"

[[package]]
name = "workshop-rs-cli"
version_group = "workshop-rs"
