name: Release-plz

on:
  push:
    branches: [main]

jobs:
  release-plz:
    uses: wrightkit/.github/.github/workflows/release-plz-crates.yml@29733ebbe8ff39f38401d1dc93c3c680651f2a5b
    permissions:
      contents: write
      pull-requests: write
    secrets:
      github-token: ${{ secrets.GH_TOKEN }}
      cargo-registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
