name: Release-plz

on:
  push:
    branches: [main]

jobs:
  release-plz:
    uses: wrightkit/.github/.github/workflows/release-plz-crates.yml@66fff829662bf235c7322194b4bafafba2a0f97e
    permissions:
      contents: write
      pull-requests: write
    secrets:
      github-token: ${{ secrets.GH_TOKEN }}
      cargo-registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
